spring:
  datasource:
    url: jdbc:mysql://test-dev:3306/test_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
